import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import InsightArticleClient from './InsightArticleClient';
import { createClient } from '@supabase/supabase-js';

// Server-side Supabase client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const supabase = createClient(supabaseUrl, supabaseKey);

interface Props {
  params: Promise<{ slug: string }>;
}

export const revalidate = 0; // No cache - always fetch fresh data

// Generate static params for all articles (for SSG/ISR)
export async function generateStaticParams() {
  const { data: posts } = await supabase
    .from('insights_posts')
    .select('slug')
    .eq('is_published', true);
    
  return (posts || []).map((post) => ({
    slug: post.slug,
  }));
}

// Generate dynamic metadata for each article
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  
  const { data: post } = await supabase
    .from('insights_posts')
    .select('*, seo:seo_metadata(*)')
    .eq('slug', slug)
    .single();
  
  if (!post) {
    return {
      title: 'Article Not Found | BPOC.IO',
    };
  }

  return {
    title: post.seo?.meta_title || `${post.title} | BPOC.IO Insights`,
    description: post.seo?.meta_description || post.description,
    keywords: post.seo?.keywords?.join(', ') || `${post.category}, BPO, ${post.title}, Philippines outsourcing, remote work`,
    authors: [{ name: post.author }],
    openGraph: {
      title: post.seo?.meta_title || post.title,
      description: post.seo?.meta_description || post.description,
      url: `https://www.bpoc.io/insights/${post.slug}`,
      type: 'article',
      publishedTime: post.published_at || post.created_at,
      authors: [post.author],
      images: [
        {
          url: post.hero_url || post.seo?.og_image || '/images/og-insights.jpg',
          width: 1200,
          height: 630,
          alt: post.title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: post.seo?.meta_title || post.title,
      description: post.seo?.meta_description || post.description,
      images: [post.hero_url || post.seo?.og_image || '/images/og-insights.jpg'],
    },
    alternates: {
      canonical: post.seo?.canonical_url || `https://www.bpoc.io/insights/${post.slug}`,
    },
  };
}

export default async function InsightArticlePage({ params }: Props) {
  const { slug } = await params;
  
  const { data: post } = await supabase
    .from('insights_posts')
    .select('*, seo:seo_metadata(*)')
    .eq('slug', slug)
    .single();

  if (!post) {
    notFound();
  }

  // Fetch related posts (simple logic: same category)
  const { data: relatedPosts } = await supabase
    .from('insights_posts')
    .select('title, slug, read_time')
    .eq('category', post.category)
    .neq('id', post.id)
    .eq('is_published', true)
    .limit(3);

  // Fetch explicit internal links (Link Manager)
  const { data: internalLinks } = await supabase
    .from('internal_links')
    .select('anchor_text, target_post:insights_posts!internal_links_target_post_id_fkey(slug, title)')
    .eq('source_post_id', post.id);

  // ============================================
  // JSON-LD SCHEMA MARKUP FOR RICH SNIPPETS
  // ============================================

  // Article Schema (always present)
  const articleSchema = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: post.title,
    description: post.description,
    image: post.hero_url || 'https://www.bpoc.io/images/og-insights.jpg',
    datePublished: post.published_at || post.created_at,
    dateModified: post.updated_at,
    author: {
      '@type': 'Person',
      name: post.author,
    },
    publisher: {
      '@type': 'Organization',
      name: 'BPOC.IO',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.bpoc.io/icon.svg',
      },
    },
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': `https://www.bpoc.io/insights/${post.slug}`,
    },
    articleSection: post.category,
    wordCount: post.content.split(' ').length,
  };

  // Extract additional schemas from SEO metadata (generated by pipeline Stage 7)
  const schemaData = post.seo?.schema_data || {};
  const breadcrumbSchema = schemaData.breadcrumb;
  const faqSchema = schemaData.faq;
  const howToSchema = schemaData.howTo;

  return (
    <>
      {/* Article Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />

      {/* Breadcrumb Schema (if exists) */}
      {breadcrumbSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
        />
      )}

      {/* FAQ Schema (if exists) */}
      {faqSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />
      )}

      {/* HowTo Schema (if exists) */}
      {howToSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }}
        />
      )}

      <InsightArticleClient post={post} relatedPosts={relatedPosts || []} internalLinks={internalLinks || []} />
    </>
  );
}
