import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase/admin';

// DEV ONLY — Creates test accounts for all user types
// Hit GET /api/dev/seed-test-accounts to create them
// Returns login credentials for each

const TEST_PASSWORD = 'Test1234!';

const TEST_ACCOUNTS = {
  admin: {
    email: 'test-admin@bpoc.io',
    firstName: 'Test',
    lastName: 'Admin',
    role: 'admin',
  },
  recruiterVerified: {
    email: 'test-recruiter@bpoc.io',
    firstName: 'Test',
    lastName: 'Recruiter',
    agencyName: 'Test BPO Agency',
    verificationStatus: 'verified',
    role: 'admin',
  },
  recruiterPendingDocs: {
    email: 'test-recruiter-pending@bpoc.io',
    firstName: 'Test',
    lastName: 'PendingRecruiter',
    agencyName: 'Pending BPO Agency',
    verificationStatus: 'pending_documents',
    role: 'admin',
  },
  recruiterJunior: {
    email: 'test-junior@bpoc.io',
    firstName: 'Test',
    lastName: 'JuniorRecruiter',
    agencyName: 'Junior Test Agency',
    verificationStatus: 'pending_authorization_head',
    role: 'recruiter',
  },
  candidate: {
    email: 'test-candidate@bpoc.io',
    firstName: 'Test',
    lastName: 'Candidate',
  },
};

async function createOrGetUser(email: string, firstName: string, lastName: string, role: string) {
  // Check if user exists
  const { data: existingUsers } = await supabaseAdmin.auth.admin.listUsers();
  const existing = existingUsers?.users?.find((u: any) => u.email === email);
  
  if (existing) {
    // Reset password to known value
    await supabaseAdmin.auth.admin.updateUser(existing.id, { password: TEST_PASSWORD });
    return existing.id;
  }

  // Create new user
  const { data, error } = await supabaseAdmin.auth.admin.createUser({
    email,
    password: TEST_PASSWORD,
    email_confirm: true,
    user_metadata: {
      first_name: firstName,
      last_name: lastName,
      // full_name is auto-generated by auth — skip it
      role,
      admin_level: role === 'admin' ? 'admin' : role === 'recruiter' ? 'recruiter' : undefined,
    },
  });

  if (error) throw new Error(`Failed to create ${email}: ${error.message}`);
  return data.user.id;
}

export async function GET() {
  // Only allow in development / preview
  if (process.env.NODE_ENV === 'production' && !process.env.VERCEL_ENV?.includes('preview')) {
    // Allow it anyway for now during testing — remove this later
    // return NextResponse.json({ error: 'Not available in production' }, { status: 403 });
  }

  try {
    const results: any = {};

    // 1. Create Admin
    const adminId = await createOrGetUser(
      TEST_ACCOUNTS.admin.email,
      TEST_ACCOUNTS.admin.firstName,
      TEST_ACCOUNTS.admin.lastName,
      'admin'
    );
    // Ensure bpoc_users record exists (full_name is a generated column — don't insert it)
    await supabaseAdmin.from('bpoc_users').upsert({
      id: adminId,
      email: TEST_ACCOUNTS.admin.email,
      first_name: TEST_ACCOUNTS.admin.firstName,
      last_name: TEST_ACCOUNTS.admin.lastName,
      role: 'admin',
      is_active: true,
    }, { onConflict: 'id' });

    results.admin = {
      email: TEST_ACCOUNTS.admin.email,
      password: TEST_PASSWORD,
      loginUrl: '/admin/login',
      userId: adminId,
    };

    // 2. Create Verified Recruiter
    const recVerifiedId = await createOrGetUser(
      TEST_ACCOUNTS.recruiterVerified.email,
      TEST_ACCOUNTS.recruiterVerified.firstName,
      TEST_ACCOUNTS.recruiterVerified.lastName,
      'recruiter'
    );
    // Create agency
    const agencySlug = 'test-bpo-agency';
    const { data: agency } = await supabaseAdmin
      .from('agencies')
      .upsert({
        name: TEST_ACCOUNTS.recruiterVerified.agencyName,
        slug: agencySlug,
        is_active: true,
        is_verified: true,
        documents_verified: true,
      }, { onConflict: 'slug' })
      .select()
      .single();

    if (agency) {
      await supabaseAdmin.from('agency_recruiters').upsert({
        user_id: recVerifiedId,
        agency_id: agency.id,
        email: TEST_ACCOUNTS.recruiterVerified.email,
        first_name: TEST_ACCOUNTS.recruiterVerified.firstName,
        last_name: TEST_ACCOUNTS.recruiterVerified.lastName,
        role: 'admin',
        is_active: true,
        can_post_jobs: true,
        can_manage_applications: true,
        can_invite_recruiters: true,
        can_manage_clients: true,
        verification_status: 'verified',
        is_verified: true,
        profile_completion_percentage: 100,
      }).select().single();
    }

    results.recruiterVerified = {
      email: TEST_ACCOUNTS.recruiterVerified.email,
      password: TEST_PASSWORD,
      loginUrl: '/recruiter/login',
      userId: recVerifiedId,
      agencyId: agency?.id,
      status: 'verified',
    };

    // 3. Create Pending Documents Recruiter
    const recPendingId = await createOrGetUser(
      TEST_ACCOUNTS.recruiterPendingDocs.email,
      TEST_ACCOUNTS.recruiterPendingDocs.firstName,
      TEST_ACCOUNTS.recruiterPendingDocs.lastName,
      'recruiter'
    );
    const pendingSlug = 'pending-bpo-agency';
    const { data: pendingAgency } = await supabaseAdmin
      .from('agencies')
      .upsert({
        name: TEST_ACCOUNTS.recruiterPendingDocs.agencyName,
        slug: pendingSlug,
        is_active: true,
        is_verified: false,
      }, { onConflict: 'slug' })
      .select()
      .single();

    if (pendingAgency) {
      await supabaseAdmin.from('agency_recruiters').upsert({
        user_id: recPendingId,
        agency_id: pendingAgency.id,
        email: TEST_ACCOUNTS.recruiterPendingDocs.email,
        first_name: TEST_ACCOUNTS.recruiterPendingDocs.firstName,
        last_name: TEST_ACCOUNTS.recruiterPendingDocs.lastName,
        role: 'admin',
        is_active: true,
        can_post_jobs: true,
        can_manage_applications: true,
        can_invite_recruiters: true,
        can_manage_clients: true,
        verification_status: 'pending_documents',
        is_verified: false,
        profile_completion_percentage: 50,
      }).select().single();
    }

    results.recruiterPendingDocs = {
      email: TEST_ACCOUNTS.recruiterPendingDocs.email,
      password: TEST_PASSWORD,
      loginUrl: '/recruiter/login',
      userId: recPendingId,
      agencyId: pendingAgency?.id,
      status: 'pending_documents',
    };

    // 4. Create Junior Recruiter (pending auth head)
    const recJuniorId = await createOrGetUser(
      TEST_ACCOUNTS.recruiterJunior.email,
      TEST_ACCOUNTS.recruiterJunior.firstName,
      TEST_ACCOUNTS.recruiterJunior.lastName,
      'recruiter'
    );
    const juniorSlug = 'junior-test-agency';
    const { data: juniorAgency } = await supabaseAdmin
      .from('agencies')
      .upsert({
        name: TEST_ACCOUNTS.recruiterJunior.agencyName,
        slug: juniorSlug,
        is_active: true,
        is_verified: false,
      }, { onConflict: 'slug' })
      .select()
      .single();

    if (juniorAgency) {
      await supabaseAdmin.from('agency_recruiters').upsert({
        user_id: recJuniorId,
        agency_id: juniorAgency.id,
        email: TEST_ACCOUNTS.recruiterJunior.email,
        first_name: TEST_ACCOUNTS.recruiterJunior.firstName,
        last_name: TEST_ACCOUNTS.recruiterJunior.lastName,
        role: 'recruiter',
        is_active: true,
        can_post_jobs: true,
        can_manage_applications: true,
        can_invite_recruiters: false,
        can_manage_clients: false,
        verification_status: 'pending_authorization_head',
        is_verified: false,
        profile_completion_percentage: 25,
      }).select().single();
    }

    results.recruiterJunior = {
      email: TEST_ACCOUNTS.recruiterJunior.email,
      password: TEST_PASSWORD,
      loginUrl: '/recruiter/login',
      userId: recJuniorId,
      agencyId: juniorAgency?.id,
      status: 'pending_authorization_head',
    };

    // 5. Create Candidate
    const candidateId = await createOrGetUser(
      TEST_ACCOUNTS.candidate.email,
      TEST_ACCOUNTS.candidate.firstName,
      TEST_ACCOUNTS.candidate.lastName,
      'candidate'
    );
    await supabaseAdmin.from('candidates').upsert({
      id: candidateId,
      first_name: TEST_ACCOUNTS.candidate.firstName,
      last_name: TEST_ACCOUNTS.candidate.lastName,
      slug: 'test-candidate',
      is_active: true,
    }, { onConflict: 'id' });

    await supabaseAdmin.from('candidate_profiles').upsert({
      candidate_id: candidateId,
      bio: 'Test candidate for development testing',
      location: 'Manila, Philippines',
      location_city: 'Manila',
      location_country: 'Philippines',
    }, { onConflict: 'candidate_id' });

    results.candidate = {
      email: TEST_ACCOUNTS.candidate.email,
      password: TEST_PASSWORD,
      loginUrl: '/candidate/login',
      userId: candidateId,
    };

    return NextResponse.json({
      message: '✅ Test accounts created/reset successfully',
      password: TEST_PASSWORD,
      accounts: results,
      quickLinks: {
        admin: `https://www.bpoc.io/admin/login`,
        recruiterVerified: `https://www.bpoc.io/recruiter/login`,
        recruiterPendingDocs: `https://www.bpoc.io/recruiter/login`,
        recruiterJunior: `https://www.bpoc.io/recruiter/login`,
        candidate: `https://www.bpoc.io/candidate/login`,
      },
    });
  } catch (error: any) {
    console.error('Seed error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
